/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package marrylab;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.List;
import java.util.ArrayList;

/*class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}*/


class LaboratoryTest {
	@Test
	public void testRemoveStudent() {
        /*
         * テスト用データの初期設定
         */
        Laboratory laboratory = new Laboratory("Test"); 
        Student student1 = new Student(1,"田中太郎", 1.5);
        Student student2 = new Student(2,"森真一", 2.5);
        Student student3 = new Student(3,"小林勝", 3.5);
        laboratory.addStudent(student1);
        laboratory.addStudent(student2);
        laboratory.addStudent(student3);
        laboratory.updateCapacity(2);

        /*
         * 理想の除名後生徒リスト
         */
        List<Student> expectedList = new ArrayList<>();
        expectedList.add(student3);
        expectedList.add(student2);

        /*
         * テストリストを出力、理想のリストと一致するか確認
         */
        laboratory.removeStudent();
        List<Student> StudentList = new ArrayList<>();
        StudentList = laboratory.studentList();

        assertEquals(expectedList, StudentList);
	}
}
